<a href="https://colab.research.google.com/github/Kavya-1708/python_libraries_EDA_Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1, 2, 3])             #1D array
b = np.array([(1, 2, 3), (4, 5, 6)]) #2D array
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((2, 2), 2)

array([[2, 2],
       [2, 2]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])